# Generated by Django 5.2.8 on 2025-12-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_attachment_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or FontAwesome class (e.g., 📱 or fa-laptop)', max_length=50),
        ),
    ]
