# Generated by Django 5.2.8 on 2025-12-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
