# Generated by Django 5.2.8 on 2025-12-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_message_notified_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
