# Generated by Django 5.2.8 on 2025-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='notified',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
