# Generated by Django 5.2.8 on 2026-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_message_notified_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolutionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
